# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PublishRelease

on:
  push:
    tags:
      - '1*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
    - run: yarn build
    - uses: "marvinpinto/action-automatic-releases@latest"
      id: publish
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "Mousewheel image zoom v${{steps.publish.outputs.automatic_release_tag}}"
        prerelease: true
        files: |
          manifest.json
          main.js
    
